############################
## CHANGE THESE
############################

baseURL: 'https://devilsu.github.io'
title: 'Yang-Hsi Su'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'