############################
## Author
############################

author:
  name: "Yang-Hsi Su"
  # image: profile_dvs.jpg
  image: profile_yhs_2020.png
  greeting: "PhD Candidate (ABD!) :calendar:"
  # icon: ":custard:"

############################
## Links
############################

links:
  # - email: mailto:devilsu@umich.edu
  - linkedin: https://www.linkedin.com/in/devilsu/
  - github: https://github.com/DevilSu
  - facebook: https://www.facebook.com/yanghsi.su
  - instagram: https://www.instagram.com/dvs_work/
  
 

###############################
## OpenGraph & Twitter Cards
###############################

title: "Qubt Theme"
description: "Demo site build with Qubt & Hugo"
images:
  - thumbnail.jpeg